blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'



urlpatterns = [
    path('', views.index, name='home'),
    path('<str:blog_id>/', views.single_post, name='post'),
]

blog/posts/models.py
from distutils.command.upload import upload
from django.db import models
from datetime import datetime

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=150)
    sub_title = models.CharField(max_length=500, blank=True)
    body = models.TextField()
    image = models.ImageField(upload_to="media/images")
    created = models.DateTimeField(default=datetime.now, blank=True)
    
    
    def __str__(self):
        return self.title

blog/posts/views.py
from django.shortcuts import render, get_list_or_404
from . models import Post

# Create your views here.


def index(request):
    
    posts = Post.objects.all()
    context = {"post":posts}
    return render(request, 'index.html', context)


def single_post(request, blog_id):
    blog = get_list_or_404(Post, pk=blog_id)
    detail =  {"posts":blog}
    return render(request, 'posts.html',detail)

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/variables.css' %}">
    <title>Tech Init</title>
</head>
<body>    
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'posts:home' %}">Tech Init</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'posts:home' %}">Home</a>
              </li>
          
            </ul>
            <span class="navbar-text">
              more
            </span>
          </div>
        </div>
      </nav>
<div class="container">

    {% block content %}

    {% endblock %}
</div>
</div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
 
</body>
</html>

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- ======= Hero Slider Section ======= -->
    <section id="hero-slider" class="hero-slider">
        <div class="container-md" data-aos="fade-in">
          <div class="row">
            <div class="col-12">
                    <a href="{% url 'posts:home'%}" class="img-bg d-flex align-items-end" style="background-image: url({% static 'img/post-slide-2.jpg' %});">
                      <div class="img-bg-inner">
                        <h2>Welcome to Tech Init</h2>
                        <p>We make inspiring tech stories accessible to all</p>
                      </div>
                    </a>
                  </div>
        </div>
        </div>
        </div>
          </div>
        </div>
      </section><!-- End Hero Slider Section -->


      
    <!-- ======= Post Grid Section ======= -->
    <section id="posts" class="posts">
        <div class="container-fluid" data-aos="fade-up">
         
            <div class="row">
         {% for post in post reversed %}

            <div class="col-md-4">
              <div class="post-entry-1 lg">
                <a href="{% url 'posts:post' post.id %}"><img src="{{ post.image.url }}" alt="" class="img-fluid"></a>
               <a href="{% url 'posts:post' post.id %}"><h3>{{post.title}}</h3></a> 
                <div class="post-meta"><span class="mx-1"></span> <span>{{ post.sub_title }}</span></div>
                <p class="mb-4 d-block">{{ post.body | truncatewords:30 }}</p>
                <div class="post-meta"><span class="date">Date:</span> <span class="mx-1">&bullet;</span> <span>{{ post.created }}</span></div>

            </div>
          </div> <!-- End .row -->
          {% endfor %}
        </div>
        
        </div>
    
      </section> <!-- End Post Grid Section -->

{% endblock %}

blog/templates/posts.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

{% for post in posts %}


<div class="col-md-8">
    <div class="post-entry-1 lg">
      
      <a href="{% url 'posts:post' post.id %}"><img src="{{ post.image.url }}" alt="" class="img-fluid"></a>
     <a href="{% url 'posts:post' post.id %}"><h3>{{ post.title }}</h3></a> 
      <div class="post-meta"><span class="mx-1"></span> <span>{{ post.sub_title }}</span></div>
      <p class="mb-4 d-block">{{ post.body }}</p>
  </div>
</div> <!-- End .row -->

</div>

</div>

</section> <!-- End Post Grid Section -->

{% endfor %}
{% endblock %}