retailshop/retailshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retailshop/store/urls.py
from django.urls import path
from . import views
app_name = 'store'





urlpatterns = [ 
         
              path('', views.ProductListView.as_view(), name='home'),
             
              path('product/<str:pk>', views.ProductDetailView.as_view(), name='details'),
              path('products/add/', views.AddProductView.as_view(), name='add_product'),
              path('products/update/<int:pk>/', views.UpdateProductView.as_view(), name='update'),
              path('products/delete/<int:pk>/', views.DeleteProductView.as_view(), name='delete'),
              path('products/mylistings', views.listings, name='listings'),
              ]

retailshop/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='createprofile'),
    path('sellerprofile/<int:id>', views.seller_profile, name='sellerprofile'),
]

retailshop/store/models.py
from audioop import reverse
from email.mime import image
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    image = models.ImageField(upload_to="media/images")
    des = models.CharField(max_length=250)
    
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('store:listings')

retailshop/users/models.py
from distutils.command.upload import upload
from email.policy import default
import imp
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures')
    contact_number = models.CharField(max_length=100, default='08111xxx999')
    gender = models.CharField(max_length=8, default=False)
    business = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        return self.user.username

retailshop/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'example@gmail.com'}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'focus:outline-none','placeholder':'john_doe'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    
    class Meta:
        model = User
        
        fields = ("username", "email", "password1", "password2")
        
    def save(self,commit=True):
        user = super(NewUserForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    

retailshop/store/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.



# def index(request):
#     from django.core.paginator import Pagignator
#     page_obj = goods = Product.objects.all()
'''
            Search option
            
    # product_name = request.GET.get('product_name')
    if product_name != '' and proeduct_name is not None:
            page_obj = goods.filter(title__icontains=product_name)
'''
#     paginator = Paginator(page_obj,6)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     
#     context = {'page_obj':page_obj}
#     return render(request, 'store/index.html',context)
#


#class base view for product

class ProductListView(ListView):
    model = Product
    template_name = 'store/index.html'
    context_object_name = 'good'
    paginate_by = 6
    


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/details.html'
    context_object_name = 'product'

# def details(request,product_id):
#     product = Product.objects.get(id=product_id)
#     return render(request, 'store/details.html', {'product':product})



#Class based view to add a product

class AddProductView(CreateView):
    model = Product
    fields = ['title','price','des','image','seller']
    #product_form.html


'''def add_product(request):
    
    if request.method == 'POST':
        title = request.POST.get('title')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        image = request.FILES['upload']
        seller = request.user
        
        product = Product(seller=seller, title=title, price=price, des=desc, image=image)
        product.save()
    
    return render(request, 'store/addproduct.html') '''


#Update View...



'''def update_product(request,id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product.title = request.POST.get('title')
        product.price = request.POST.get('price')
        product.des = request.POST.get('desc')
        product.image = request.FILES['upload']
        
        product.save()
        return redirect('store:home')
        
    return render(request, 'store/update_product.html', {'product':product})'''



class UpdateProductView(UpdateView):
    model = Product
    fields = ['title','price','des','image','seller']
    template_name_suffix = '_update_form'
    
    
    

# def delete(request, id):
#     product = Product.objects.get(id=id)
#     if request.method == 'POST':
#         product.delete()
#         return redirect('store:listings')
#     return render(request, 'store/delete.html', {'product':product})


class DeleteProductView(DeleteView):
    model = Product
    success_url = reverse_lazy('store:listings')

@login_required
def listings(request):
    products = Product.objects.filter(seller=request.user)
    
    return render(request,'store/listings.html', {'products':products})

retailshop/users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm 
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('store:home')
    form = NewUserForm()
    return render(request, 'users/register.html', {'form':form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')



def create_profile(request):
    if request.method == 'POST':
       image = request.FILES['upload']
       phone = request.POST.get('contact')
       gender = request.POST.get('gender')
       business = request.POST.get('business')
       user = request.user
       profile = Profile(user=user, image=image,contact_number = phone, gender=gender,business=business)
       profile.save()
       
    return render(request, 'users/createprofile.html')

def seller_profile(request,id):
    seller = User.objects.get(id=id)
    return render(request, 'users/sellerprofile.html', {'seller':seller})

retailshop/store/templates/store/addproduct.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-2xl font-bold m-10">+Add Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-2/6" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4"> 

    <label for="" class="block text-gray-500 text-sm font-bold mb-2 ">Product Name</label>
    <input class="w-10/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="title" placeholder="Laptop" id="name">
    </div>

    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product price </label>
    <input  class=" w-10/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="price" placeholder="e.g:500 " id="price">
    </div>   
    
    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Description</label>
    <input  class="w-10/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="des" placeholder="core i7Hp laptop" id="des">
    </div>

    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product Image</label>
        <input class="py-2"   type="file" accept="image/*" name="upload" id="upload">
    </div>
<div>

    <input class=" w-10/12 bg-green-500 text-white px-5 py-2" type="submit" value="Add Product">
</div>
</form>

{% endblock %}

retailshop/store/templates/store/delete.html
{% extends 'base.html' %}


{% block content %}
<h2 class="text-2xl m-10 font-bold">Delete product</h2>

<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" action="" method="POST">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Are you sure you want to delete this product</label>
    </div>
    <div class="mb-4">
        <label for="">
        {{product.title}}
    </label>
</div>
<div class="mb-4">
    <img class="w-20 h-20" src="{{ product.image.url }}" alt="">
</div>
<input type="submit" class="bg-red-500 text-white px-5 py-2" value="Confirm" id="confirm">
<a class="button bg-green-500 text-white px-5 py-3" href="{% url 'store:home' %}">Cancel</a>
</form>

{% endblock %}

retailshop/store/templates/store/details.html
{% extends 'base.html' %}


{% block content %}

<div class="flex p-10 w-3/5 ml-10 h-200">
    <img src="{{ product.image.url }}" class="w-1/3" alt="{{ product.title }}">
    <div class="w-2/3 text-xl ml-5">
   
    <div class="mt-5">{{ product.title }}</div>
    <div class="mt-5 text-green-500"> &#x20A6;{{ product.price }} </div>
    <div class="mt-5 text-gray-700">{{ product.des }}</div>
    <div class="mt-5 text-gray-700">  Posted by: <a href="{% url 'users:sellerprofile' product.seller.id %}">{{product.seller}}</a>  </div>
    <div class="text-gray-700">for more info: {{product.seller.profile.contact_number}}</div>
   
   </div>
</div>





{% endblock %}

retailshop/store/templates/store/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left " >
        <h1 class="text-4xl text-extrabold justify-center text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Premium Products</span>
            <span class="block justify-center text-green-500 xl:inline">Non-premium Prices</span>
        </h1>

        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality products aross borders on free shipping</p>
    </div>
</main>

 
<div class="flex mt-5 pl-12 pt-10">

<h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500"> Recent Products </h2>

</div>

<div class="mt-5 p-10 justify-center">
    <h2>Search Products</h2>
    <form>
        <input class="font-bold text-gray-700 w-3/12 border p-1" name="product_name" id="product_name" placeholder="Search for a product" type="text" method="GET">

    </form>

</div>


<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-3 lg:grid-3 gap-5">
<!-- Card -->

{% for item in good %}

<a href="{% url 'store:details' item.id %}">

<div class="rounded overflow-hidden shadow-lg">

    <img src="{{ item.image.url }}" class="w-3/6" alt="{{ item.title }}">
    <div class="px-5 py-4">
        <div class="px-6 py-4">
            <div class="font-bold text-xl mb-2">
                {{ item.title }} </div>

              <div class="font-bold text-xl text-green-500 mb-2">
                &#8358; {{ item.price }}
              </div>
              <p class="text-gray-700 text-base">{{ item.des }}</p>
              <div class="py-2 text-gray-500">
                  <hr>
                  <strong>Available at: </strong>  <span class="text-indigo-700">{{item.seller}}
                </span>              </div>
        </div>
    </div>
    </div>


</a>
{% endfor %}

</div>


<!-- pagination page -->
<div class="pagination flex justify-center items-center ">
    <span>
        {% if page_obj.has_previous %}
        <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relattive text-green-500 border-green-500 z-10" href="?page=1">First </a>
        <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relattive text-green-500 border-green-500 z-10" href="?page={{page_obj.previous_page_number}}">Preivous</a>
        {% endif %}
        <span>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} - 
        </span>

        {% if page_obj.has_next %}

        <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relattive text-green-500 border-green-500 z-10" href="?page={{page_obj.next_page_number}}">Next </a>
        <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relattive text-green-500 border-green-500 z-10" href="?page={{ page_obj.paginator.num_pages }}">last</a>

        {% endif %}
       
    </span>
</div>

 


{% endblock %}

retailshop/store/templates/store/listings.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="sm:text-center lg:text-left">
        <h1 class="text-4xl text-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">All Products</span>
        </h1>

        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality products aross borders on free shipping</p>
    </div>
</main>

 
<div class="flex mt-5 p-10 justify-center">

<h2 class="text-2xl font-bold font-normal mt-0 mb-2 text-gray-500"> My Listings </h2>

</div>

<!-- Card -->

{% for item in products %}
<div class="itemcontainer flex shadow-md m-10 p-10"> 

    <span class="w-1/4"> 
    <img src="{{ item.image.url }}" class="w-60 h-60" alt="{{ item.title }}">
</span>

  <span class="w-2/5"> 

    <div class="font-bold mt-10 ßtext-gray-500">
        {{ item.title }} 
    </div>
    
    <div class="font-bold text-xl text-green-500 mb-2">
        &#8358; {{ item.price }}
      </div>
      <p class="text-gray-700 text-base">{{ item.des }}</p>     
    </span>

             
    <span class="w-1/5 my-10 ml-10">
        <a class="bg-green-500 text-white -font-bold px-5 py-2" href="{% url 'store:update' item.id %}">Edit</a>
    </span>

    <span class="w-1/5 my-10 ">
        <a class="bg-red-500 text-white -font-bold px-5 py-2" href="{% url 'store:delete' item.id %}">Delete</a>
    </span>
              

</div>
{% endfor %}





 


{% endblock %}

retailshop/store/templates/store/product_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<h2 class="text-2xl m-10 font-bold">Delete product</h2>

<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" action="" method="POST">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Are you sure you want to delete {{ object }}</label>
    </div>
    <div class="mb-4">
        <label for="">
        {{form}}
    </label>
</div>
<div class="mb-4">
    <img class="w-20 h-20" src="{{ product.image.url }}" alt="">
</div>
<input type="submit" class="bg-red-500 text-white px-5 py-2" value="Confirm" id="confirm">
<a class="button bg-green-500 text-white px-5 py-3" href="{% url 'store:home' %}">Cancel</a>
</form>

{% endblock %}

retailshop/store/templates/store/product_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="text-2xl font-bold m-10">+Add Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-2/6" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4"> 

    <label for="" class="block text-gray-500 text-sm font-bold mb-2">Product Name</label>
    
        <div class=" w-11/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700""> 

            {{ form.title }}

        </div>
    
    </div>

    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2 "  for="">Product price </label>
    <div class=" w-11/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
        {{form.price}}
    </div>
    </div>   
    
    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Description</label>
    <div class="w-11/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
        {{form.des}}
    </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product Image</label>
        <div class="py-2">
            {{form.image}}
        </div>
    </div>
    <div class="mb-4" hidden>
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product Image</label>
        <div class="py-2">
            {{form.seller}}
        </div>
    </div>

<div>

    <input class=" w-10/12 bg-green-500 text-white px-5 py-2" type="submit" value="Add Product">
</div>
</form>

{% endblock %}

retailshop/store/templates/store/product_update_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="text-2xl font-bold m-10">+Add Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-2/6" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4"> 

    <label for="" class="block text-gray-500 text-sm font-bold mb-2">Product Name</label>
    
        <div class=" w-11/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700""> 

            {{ form.title }}

        </div>
    
    </div>

    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2 "  for="">Product price </label>
    <div class=" w-11/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
        {{form.price}}
    </div>
    </div>   
    
    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Description</label>
    <div class="w-11/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
        {{form.des}}
    </div>
    </div>
    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product Image</label>
        <div class="py-2">
            {{form.image}}
        </div>
    </div>
    <div class="mb-4" hidden>
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product Image</label>
        <div class="py-2">
            {{form.seller}}
        </div>
    </div>

<div>

    <input class=" w-10/12 bg-green-500 text-white px-5 py-2" type="submit" value="Update">
</div>
</form>

{% endblock %}

retailshop/store/templates/store/update_product.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-2xl font-bold m-10">+ Update Product</h1>
<form class="bg-white shadow-md m-10 px-8 py-8 w-2/6" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4"> 

    <label for="" class="block text-gray-500 text-sm font-bold mb-2 ">Product Name</label>
    <input class="w-10/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="title" placeholder="Laptop" id="name" value="{{ product.title }}">
    </div>

    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product price </label>
    <input  class=" w-10/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" value="{{ product.price }}" name="price" placeholder="e.g:500 " id="price">
    </div>   
    
    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Description</label>
    <input  class="w-10/12 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="desc" value="{{ product.des }}" placeholder="core i7Hp laptop" id="des">
    </div>

    <div class="mb-4">
        <label class="block text-gray-500 text-sm font-bold mb-2" for="">Product Image</label>
        <img class="w-20 h-20" src="{{ product.image.url }}" alt="">
        <input class="py-2"   type="file" accept="image/*" name="upload" id="upload">
    </div>
<div>

    <input class=" w-10/12 bg-green-500 text-white px-5 py-2" type="submit" value="Update">
</div>
</form>

{% endblock %}

retailshop/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'store/styles.css' %}">

    <title>online retailer</title>
  </head>
  <body>

    <nav class="bg-white shadow-lg">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">

                    <div >
                        <a href="{% url 'store:home' %}" class="flex items-center px-2 py-5">
                        <img class="h-8 w-8" src="{% static 'store/images/shop_logo.png' %}" alt="">
                        <span class="text-gray-500 font-semibold text-lg">&nbsp; Retail Shop </span>
                    </a>
                    </div>

                <div class="items-center flex space-x-1">
                    <a href="{% url 'store:home' %}" class="px-2 py-5 text-gray-500 text-semibold">Home</a>
                    <a href="{% url 'store:add_product' %}" class="px-2 py-5 text-gray-500 text-semibold">Post Product</a>
                    <a href="" class="px-2 py-5 text-gray-500 text-semibold">Contact</a>
                   {% if user.is_authenticated %}
                   <a href="{% url 'users:logout'%}" class="px-10 py-5 text-gray-500 text-semibold"> {{user.username}} - Logout</a>
                    <a href="{% url 'store:listings' %}" class="pl-40 py-5 text-gray-500 text-semibold"> My listings </a>
                    <a href="{% url 'users:profile'%}" class="px-8 py-5 text-gray-500 text-semibold"> profile </a>

                    {% else %}
                   <a href="{% url 'users:login'%}" class="px-10 py-5 text-gray-500 text-semibold">Login</a>
                   {% endif %}
                </div>

        </div>
    </div>
</div>
    </nav>





 
    {% block content %}
    {% endblock %}
 

  </body>
</html>